// Mobile-side mirror of `src/utils/instructorInsights.js#buildProgressReportText`.
// Same output shape so an instructor sharing from web vs mobile produces the
// same WhatsApp/email text.

import type { Lesson, Student } from "../types";

const SKILL_DEFINITIONS: Array<{ key: string; label: string }> = [
  { key: "cockpitChecks", label: "Cockpit checks" },
  { key: "movingOff", label: "Moving off and stopping" },
  { key: "mirrors", label: "Mirrors and signals" },
  { key: "useOfSpeed", label: "Use of speed" },
  { key: "junctions", label: "Junctions and emerging" },
  { key: "roundabouts", label: "Roundabouts" },
  { key: "pedestrianCrossings", label: "Pedestrian crossings" },
  { key: "positioning", label: "Position and lane discipline" },
  { key: "awareness", label: "Awareness and planning" },
  { key: "dualCarriageways", label: "Dual carriageways" },
  { key: "independentDriving", label: "Independent driving" },
  { key: "parallelParking", label: "Parallel parking" },
  { key: "forwardParking", label: "Forward bay parking" },
  { key: "reverseParking", label: "Reverse bay parking" },
];

function statusLabel(value: number): string {
  const v = Math.max(0, Math.min(5, Math.round(value || 0)));
  if (v === 0) return "Not started";
  if (v <= 2) return "Introduced";
  if (v === 3) return "Needs work";
  if (v === 4) return "Competent";
  return "Test ready";
}

function aggregateRatings(lessons: Lesson[]): Record<string, number> {
  // Take the most recent rating for each skill.
  const result: Record<string, number> = {};
  // lessons are sorted newest first by caller; iterate in that order so the
  // first non-zero rating wins.
  for (const lesson of lessons) {
    const ratings = lesson.skillRatings || {};
    for (const [key, value] of Object.entries(ratings)) {
      if (typeof value !== "number" || value <= 0) continue;
      if (result[key] === undefined) result[key] = value;
    }
  }
  return result;
}

function pad(value: string, width: number) {
  if (value.length >= width) return value;
  return value + " ".repeat(width - value.length);
}

export function buildProgressReportText(
  student: Student | null,
  lessons: Lesson[] = [],
  options: { instructorName?: string } = {},
): string {
  const studentName = student?.name || "Student";
  const instructorName = options.instructorName || "your instructor";
  const completedLessons = lessons.filter((l) => l.status && l.status !== "scheduled" && l.status !== "cancelled");
  const ratings = aggregateRatings(lessons);
  const ratedValues = Object.values(ratings).filter((v) => v > 0);
  const average = ratedValues.length
    ? ratedValues.reduce((a, b) => a + b, 0) / ratedValues.length
    : 0;
  const percent = Math.round((average / 5) * 100);

  const lines: string[] = [];
  lines.push(`App7i progress report — ${studentName}`);
  lines.push("");
  lines.push(`From: ${instructorName}`);
  lines.push(`Lessons completed: ${completedLessons.length}`);
  lines.push(`Overall progress: ${percent}%`);
  lines.push("");
  lines.push("DVSA syllabus progress:");
  for (const skill of SKILL_DEFINITIONS) {
    lines.push(`  ${pad(skill.label, 34)} ${statusLabel(ratings[skill.key] || 0)}`);
  }

  // Recent skill notes — last 3 lessons that have any per-skill comment
  const recent = completedLessons.slice(0, 3).filter(
    (l) => l.skillNotes && Object.keys(l.skillNotes).length > 0,
  );
  if (recent.length > 0) {
    lines.push("");
    lines.push("Recent lessons:");
    for (const lesson of recent) {
      lines.push("");
      lines.push(`• ${lesson.date || "Recent lesson"}`);
      for (const [key, comment] of Object.entries(lesson.skillNotes || {})) {
        if (!comment) continue;
        const def = SKILL_DEFINITIONS.find((s) => s.key === key);
        if (def) lines.push(`    ${def.label}: ${comment}`);
      }
    }
  }

  lines.push("");
  lines.push("Generated by App7i — driving instructor app");
  return lines.join("\n");
}
